### ISSUE TITLE
Test suite fails on FreeBSD systems

### ISSUE THREAD

**Issue by eserte** [atrodo/App-MechaCPAN#10]
On all of my FreeBSD smokers the test suite fails:
```
#  - Could not find perl to configure at /home/cpansand/.cpan/build/2018100908/App-MechaCPAN-0.24-0/blib/lib/App/MechaCPAN/Perl.pm line 99.

#   Failed test 'Can install "perl" from a tar.gz'
#   at t/11_perl.t line 13.
#          got: '-1'
#     expected: '0'
# Looks like you failed 1 test of 1.
t/11_perl.t ................ 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 
t/12_perl__get_targz.t ..... ok
#  - Could not find perl to configure at /home/cpansand/.cpan/build/2018100908/App-MechaCPAN-0.24-0/blib/lib/App/MechaCPAN/Perl.pm line 99.

#   Failed test 'Can install "perl" from a tar.gz'
#   at t/13_perl_smart_tests.t line 29.
#          got: '-1'
#     expected: '0'
... (etc) ...
```

**Comment by atrodo** [comment]
Thank you for the report. I did notice all of those failures on *BSD systems. After some investigation, I discovered that tar included with libarchive (and used by most BSD systems) does not return an error when it receives a 0 byte input, unlike GNU tar that I tested with. I've changed the code to account for this by verifying that tar in fact created files. This fix was released with 0.25 and as far as I can tell the BSDs are happier now.
