### ISSUE TITLE
How do we properly work around B::Debug deprecation warnings?

### ISSUE THREAD

**Issue by pattieja1** [atrodo/App-MechaCPAN#12]
When trying to install the WebService::Slack::WebApi module via mechacpan, it's failing the unit tests for a module it depends on due to the warnings from perl 5.28.0 that B::Debug will be removed from core perl in the next release.   Trying to specify to install B::Debug just says that it's uptodate and I still get the same errors.

Specifying --skip-tests would work around it but is not the safest solution long term or I assume building an older version of perl (say 5.26).

Is this something that the Devel::Cover module author has to deal with or can we trap the output and if the only issue is the warning similar to

`B::Debug will be removed from the Perl core distribution in the next major release. Please install it from CPAN. It is being used at /root/local/tmp/mecha_mecha_Devel-Cover-1.31.tar.gz.20180925_102242.H9ds.20180925_102242.pSwm/Devel-Cover-`

then we can internally cause the module to be re-ran but set the skip-tests flag for just that instance so we don't run the tests and it can then install?

Thoughts?

**Comment by atrodo** [comment]
So Module::CoreList, which I use to see if a distribution is core or not, will also say if a module is deprecated. I am adding code that will also consult that list and consider any depreciated modules as non-core. That should resolve Devel::Cover on 5.28+.

**Comment by atrodo** [comment]
v0.26 contains these changes and has been released.

**Comment by pattieja1** [comment]
Installing WebService::Slack::WebApi with App::MechaCPAN 0.26 on perl 5.28.0 worked without any special flags. :)
