### ISSUE TITLE
Can't locate File/Fetch.pm

### ISSUE THREAD

**Issue by eserte** [atrodo/App-MechaCPAN#20]
While File::Fetch is a core module since quite a while, it may be missing in some perl installations, for example in the perl package found on CentOS 7. This leads to the following test failure:
```
#   Failed test 'use App::MechaCPAN;'
#   at t/01_sanity.t line 5.
#     Tried to use 'App::MechaCPAN'.
#     Error:  Can't locate File/Fetch.pm in @INC (@INC contains: /home/cpansand/.cpan/build/2021081107/App-MechaCPAN-0.27-eqauUi/blib/lib /home/cpansand/.cpan/build/2021081107/App-MechaCPAN-0.27-eqauUi/blib/arch /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /home/cpansand/.cpan/build/2021081107/App-MechaCPAN-0.27-eqauUi/blib/lib/App/MechaCPAN.pm line 16.
# BEGIN failed--compilation aborted at /home/cpansand/.cpan/build/2021081107/App-MechaCPAN-0.27-eqauUi/blib/lib/App/MechaCPAN.pm line 16.
# Compilation failed in require at (eval 4) line 2.
# BEGIN failed--compilation aborted at (eval 4) line 2.
# Looks like you failed 1 test of 1.
t/01_sanity.t .............. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 
... etc ...
```
I think it does not hurt to add File::Fetch to the distribution's prerequisite list.

**Comment by atrodo** [comment]
I appreciate the ticket, while looking through the many failures from the last release, I did not notice this one. I have added all the core modules that are used into the prerequisite list to hopefully mitigate this problem.

**Comment by atrodo** [comment]
Correction for future me: I stepped through and listed all the core modules that are not core to the minimal perl package in redhat/centos. Some, like overload and File::Spec, I did not include because they did not appear to be in a separated package.
